"""Per-environment semantic-mode <-> HDBSCAN-cluster-id taxonomy.

A taxonomy is a YAML file with the schema::

    environment: <str>
    source: <path to cluster_id_to_label_*.json that seeded it>
    modes:
      "Road: On":                      [5, 6, 8, 9, 10, 11, 12]
      "Intersection: Approach/Enter":  [7]
      "Intersection: In":              [0, 1, 2]
      "Open Space":                    [3, 4]
      ...

Multiple semantic modes may map to overlapping cluster id sets — the executor
treats *any* listed id as "in this mode" when watching ``/predicted_cluster``,
and uses the **first** id as the canonical scalar ``start_cluster`` /
``goal_cluster`` in the brain-shaped linear plan.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Mapping

import yaml


class TaxonomyError(ValueError):
    """Raised for malformed taxonomy files or unknown-mode lookups."""


@dataclass(frozen=True)
class ClusterTaxonomy:
    """In-memory view of a ``cluster_map.<env>.yaml`` file."""

    environment: str
    source: str | None
    modes: Mapping[str, tuple[int, ...]]
    # Per-mode execution metadata, generated by
    # bev_pipeline.taxonomy_export.build_hierarchical_cluster_map. Optional: files
    # written before it existed simply have none, and the defaults below preserve
    # the previous behaviour exactly.
    #   accept_degraded:   coarser cluster ids that may satisfy this mode on a
    #                      LANDMARK-triggered step, where a Detect(...) predicate
    #                      carries the real evidence and the cluster is only a
    #                      permissive guard. Never applied to traverse steps.
    #   perception_backed: False when the mode is a plan-level construct in this
    #                      environment rather than something a classifier can
    #                      emit (e.g. "Intersection: In" on the real campus).
    mode_meta: Mapping[str, Mapping[str, object]] = None  # type: ignore[assignment]
    # Optional CARLA-specific spatial data.
    centroids: Mapping[str, tuple[float, float, float]] = None  # type: ignore[assignment]
    bearing_map: Mapping[str, float] = None  # type: ignore[assignment]

    # ------------------------------------------------------------------ #
    # Lookup                                                              #
    # ------------------------------------------------------------------ #
    #: mode -> axis name. Empty for single-axis maps, where every mode is an
    #: alternative to every other and union is the right merge.
    axes: dict = field(default_factory=dict)

    def __contains__(self, mode: str) -> bool:
        return self.canonical_mode(mode) is not None

    def canonical_mode(self, mode: str) -> str | None:
        r"""This taxonomy's own spelling of ``mode``, or None if it has none.

        ONE collapse rule, applied in one place. Mode names reach us in several
        spellings — the STL compiler lowercases a macro (``\Phi_{Path}`` ->
        ``path``) while the campus maps spell it ``Path``, ``Space: Open``,
        ``Road: On``. Every comparison must use the same rule: if the formula gate
        collapsed case while ``resolve`` matched exactly, ``G \Phi_{Path}`` against
        a ``Path`` taxonomy would pass validation and then raise ``TaxonomyError``
        during materialization — the crash-instead-of-retry failure
        ``validate_plan_modes`` exists to prevent.

        Collapsing ignores only case and separators, so it cannot mask a real
        typo: ``pth`` still fails.
        """
        if mode is None:
            return None
        if mode in self.modes:
            return mode
        want = _collapse_mode(mode)
        for known in self.modes:
            if _collapse_mode(known) == want:
                return known

        # Concept fallback, for names that drifted by RENAME rather than spelling:
        # `Open Space` -> `Space: Open`, `Road: On` -> `On: Path`. See mode_concepts.
        #
        # When several modes here share a concept -- `full_campus_1hz` has Approach:,
        # In: and Exit: Junction -- the tie is broken by the order they are listed in
        # CONCEPTS, core spelling first. Deterministic rather than dict order, and it
        # means `junction` resolves to `In: Junction` there instead of failing. A map
        # with two genuinely different modes under one concept would still resolve to
        # the higher-ranked one, which is why that ordering is a deliberate list and
        # not alphabetical.
        from .mode_concepts import RANK, concept_of
        want_concept = concept_of(mode)
        if want_concept is None:
            return None
        hits = [k for k in self.modes if concept_of(k) == want_concept]
        if not hits:
            return None
        return min(hits, key=lambda k: (RANK.get(k, 99), k))

    def resolve(self, mode: str) -> tuple[int, ...]:
        """Return the cluster id tuple for ``mode``.

        Raises ``TaxonomyError`` if the mode is not in the YAML.
        """
        canon = self.canonical_mode(mode)
        if canon is None:
            raise TaxonomyError(
                f"semantic mode {mode!r} not in taxonomy for environment "
                f"{self.environment!r}; legal modes: {sorted(self.modes)}"
            )
        return self.modes[canon]

    def canonical_id(self, mode: str) -> int:
        """First cluster id listed for ``mode`` — used as the scalar id brain sees."""
        ids = self.resolve(mode)
        if not ids:
            raise TaxonomyError(
                f"semantic mode {mode!r} maps to an empty cluster id list"
            )
        return ids[0]

    def accept_clusters(self, mode: str, *, degraded: bool = False) -> tuple[int, ...]:
        """Cluster ids that count as "in ``mode``", preferred-first.

        ``degraded=False`` (default) returns exactly ``resolve(mode)`` — the
        mode's own id plus anything that reaches it by subsumption. This is what
        a ``traverse`` step uses, where the cluster IS the evidence.

        ``degraded=True`` additionally appends ``mode_meta[mode].accept_degraded``
        — the coarser ids that may satisfy the step when the fine classifier does
        not fire. Only valid for ``landmark``-triggered steps; the caller is
        responsible for that gate, not this method.
        """
        ids = list(self.resolve(mode))
        if not degraded:
            return tuple(ids)
        for cid in self._meta_for(mode).get("accept_degraded", ()) or ():
            if cid not in ids:
                ids.append(int(cid))
        return tuple(ids)

    def is_perception_backed(self, mode: str) -> bool:
        """False when ``mode`` is a plan-level construct in this environment.

        Defaults to True so taxonomies written before ``mode_meta`` existed keep
        behaving as they did.
        """
        self.resolve(mode)          # raises TaxonomyError on unknown mode
        return bool(self._meta_for(mode).get("perception_backed", True))

    def _meta_for(self, mode: str) -> Mapping[str, object]:
        if not self.mode_meta:
            return {}
        return self.mode_meta.get(mode) or {}

    def modes_for_prompt(self) -> list[str]:
        """Sorted list of legal mode strings, ready to splice into the user message.

        Returned VERBATIM and unannotated: the prompt tells the generator to copy these into
        `start_mode`/`goal_mode` exactly, so decorating them here would make it emit
        "asphalt [surface]" as a mode name and fail validation. The axis goes in
        `axes_note()` instead, as a separate line.
        """
        return sorted(self.modes.keys())

    def axes_note(self) -> str:
        """One line telling the generator which AXIS each mode measures, or "" if none.

        The axis has to reach the generator or the distinction cannot be used. E.g. on
        `carla_town05_sidewalks` (axes: path/junction = topology, sidewalk/asphalt =
        surface), given only the bare names the generator can render "staying off the
        sidewalk" as `forbid_modes: ['path']` -- the TOPOLOGY axis. The comment at the
        `axes` parse site explains why the distinction matters.

        Empty when a taxonomy declares no axes, so environments without axes are
        unaffected.
        """
        if not self.axes:
            return ""
        by = {}
        for m, ax in sorted(self.axes.items()):
            by.setdefault(ax, []).append(m)
        parts = "; ".join(f"{ax}: {', '.join(ms)}" for ax, ms in sorted(by.items()))
        return ("Mode AXES -- " + parts + ". Modes on the SAME axis are alternatives; modes "
                "on DIFFERENT axes are simultaneous facts about one place. A constraint "
                "about the SURFACE underfoot (\"stay off the sidewalk\", \"keep to the "
                "asphalt\") belongs on the surface axis, NOT on the topology axis -- "
                "topologically a sidewalk IS a path, so forbidding `path` does not say it.")

    def label_for_id(self, cluster_id: int) -> str | None:
        """Inverse lookup: return any mode that contains ``cluster_id`` (or None)."""
        for mode, ids in self.modes.items():
            if cluster_id in ids:
                return mode
        return None

    def centroid_map(self) -> dict[str, list[float]]:
        """Return ``{cluster_id_str: [x, y, z]}`` or empty dict if not defined."""
        if not self.centroids:
            return {}
        return {k: list(v) for k, v in self.centroids.items()}

    def bearing_map_dict(self) -> dict[str, float]:
        """Return ``{"start_id-goal_id": degrees_relative}`` or empty dict."""
        if not self.bearing_map:
            return {}
        return dict(self.bearing_map)

    def cluster_labels(self) -> dict[int, str]:
        """``{cluster_id: mode_name}`` dict suitable for brain_controller's
        ``cluster_labels`` plan field.

        When a cluster id appears in several modes — which the subsumption lattice
        guarantees, since a junction's id is listed under ``junction`` AND under
        ``path`` — the **most specific** mode wins: the one with the fewest ids.

        Taking the first-encountered mode (YAML order) is wrong: if ``path`` is listed
        before ``junction``, every junction id is labelled ``path``. Nothing crashes —
        but a consumer asking "which neighbour is a junction?" finds none, and the
        vehicle has nowhere to go.

        Fewest-ids is the right tie-break because the exporter builds each mode's list as
        its OWN ids plus everything that reaches it by subsumption, so a coarse mode is
        always a strict superset of the fine ones under it.
        """
        out: dict[int, str] = {}
        # ascending by set size, then by name so equal-sized sets stay deterministic
        for mode, ids in sorted(self.modes.items(), key=lambda kv: (len(kv[1]), kv[0])):
            for cid in ids:
                out.setdefault(cid, mode)
        return out


# --------------------------------------------------------------------------- #
# Loading                                                                     #
# --------------------------------------------------------------------------- #

def load_taxonomy(path: str | Path) -> ClusterTaxonomy:
    """Read and validate ``path`` (a YAML file). Raises ``TaxonomyError``."""
    p = Path(path)
    if not p.exists():
        raise TaxonomyError(f"taxonomy file not found: {p}")
    try:
        raw = yaml.safe_load(p.read_text()) or {}
    except yaml.YAMLError as exc:
        raise TaxonomyError(f"could not parse YAML at {p}: {exc}") from exc
    if not isinstance(raw, dict):
        raise TaxonomyError(f"taxonomy at {p} must be a mapping at the top level")

    env = raw.get("environment")
    if not isinstance(env, str) or not env.strip():
        raise TaxonomyError(f"taxonomy at {p} is missing a non-empty 'environment' string")

    modes_raw = raw.get("modes") or {}
    if not isinstance(modes_raw, dict) or not modes_raw:
        raise TaxonomyError(f"taxonomy at {p} must declare a non-empty 'modes' mapping")

    modes: dict[str, tuple[int, ...]] = {}
    for mode, ids in modes_raw.items():
        if not isinstance(mode, str) or not mode.strip():
            raise TaxonomyError(f"mode keys must be non-empty strings; got {mode!r}")
        if not isinstance(ids, list) or not ids:
            raise TaxonomyError(
                f"mode {mode!r} must map to a non-empty list of cluster ids"
            )
        ints: list[int] = []
        for x in ids:
            if not isinstance(x, int):
                raise TaxonomyError(
                    f"cluster ids under mode {mode!r} must be ints; got {x!r}"
                )
            ints.append(x)
        modes[mode] = tuple(ints)

    # Optional: which AXIS each mode measures. Modes on the SAME axis are alternatives
    # (union); modes on DIFFERENT axes are simultaneous facts about one place, and must
    # both hold (intersection).
    #
    # This exists because a sidewalk is not a third kind of route -- topologically it IS a
    # path. What distinguishes it is the SURFACE. Modelling it as a separate topology mode
    # made `require_modes: [sidewalk]` and a formula's `G Phi_Path` merge by union into
    # "sidewalk OR road", which is satisfied by driving the whole route on the
    # carriageway -- the mission's exact opposite. On separate axes they intersect to
    # "a path whose surface is sidewalk", which is what the English said.
    axes = raw.get("axes") or {}
    source = raw.get("source")

    # Optional per-mode execution metadata (see ClusterTaxonomy.mode_meta).
    mode_meta_raw = raw.get("mode_meta") or {}
    if not isinstance(mode_meta_raw, dict):
        raise TaxonomyError(f"'mode_meta' in {p} must be a mapping if present")
    mode_meta: dict[str, dict[str, object]] = {}
    for mode, meta in mode_meta_raw.items():
        if mode not in modes:
            raise TaxonomyError(
                f"mode_meta references unknown mode {mode!r} in {p}; "
                f"legal modes: {sorted(modes)}"
            )
        if not isinstance(meta, dict):
            raise TaxonomyError(f"mode_meta[{mode!r}] in {p} must be a mapping")
        entry: dict[str, object] = {}
        if "perception_backed" in meta:
            entry["perception_backed"] = bool(meta["perception_backed"])
        if meta.get("accept_degraded") is not None:
            deg = meta["accept_degraded"]
            if not isinstance(deg, list):
                raise TaxonomyError(
                    f"mode_meta[{mode!r}].accept_degraded in {p} must be a list of ints"
                )
            ids: list[int] = []
            for x in deg:
                if not isinstance(x, int):
                    raise TaxonomyError(
                        f"mode_meta[{mode!r}].accept_degraded must contain ints; got {x!r}"
                    )
                ids.append(x)
            entry["accept_degraded"] = tuple(ids)
        # Free-form predicate hooks used when perception_backed is False.
        for key in ("enter_on", "exit_on", "requires_sensor"):
            if meta.get(key) is not None:
                entry[key] = str(meta[key])
        mode_meta[mode] = entry

    # Optional CARLA spatial data: centroids + bearing_map
    centroids_raw = raw.get("centroids") or {}
    centroids: dict[str, tuple[float, float, float]] = {}
    for k, v in centroids_raw.items():
        if isinstance(v, (list, tuple)) and len(v) >= 2:
            centroids[str(k)] = (float(v[0]), float(v[1]), float(v[2]) if len(v) > 2 else 0.0)

    bearing_map_raw = raw.get("bearing_map") or {}
    bearing_map: dict[str, float] = {str(k): float(v) for k, v in bearing_map_raw.items()}

    return ClusterTaxonomy(
        axes=axes,
        environment=env,
        source=source if isinstance(source, str) else None,
        modes=modes,
        mode_meta=mode_meta or None,
        centroids=centroids or None,
        bearing_map=bearing_map or None,
    )


# --------------------------------------------------------------------------- #
# Validation against a NavPlan                                                #
# --------------------------------------------------------------------------- #

def validate_plan_modes(plan, taxonomy: ClusterTaxonomy) -> list[str]:
    """Return a list of every mode the plan names that is not in the taxonomy.

    Walks the full branch tree. Empty list = all good. ``plan`` may be a
    ``NavPlan`` instance or a dict matching that schema.

    FOUR fields name a mode, not two. ``start_mode`` / ``goal_mode`` were the
    original pair; ``hold_mode`` (the mode a dwell step must stay in) and the
    plan-level ``forbid_modes`` (the modes it must never enter) name modes just
    as literally, and both get resolved to cluster id sets downstream by
    ``branch_materializer``; ``require_modes`` likewise. All must be checked, and
    checked the same way formulas are (see ``validate_stl_modes``): otherwise a
    plan naming a nonexistent mode is rejected while a formula naming the same
    mode is accepted, which makes plan-vs-formula comparisons asymmetric.

    Checking them here rather than letting the materializer's
    ``accept_clusters()`` raise is the difference between a retryable failure and
    a crash: this list is what ``pipeline`` feeds back to the generator so it can
    fix the spelling, while a ``TaxonomyError`` out of materialization aborts the
    run. A misspelled ``forbid_modes`` entry is the worse of the two silently —
    an unresolvable negative constraint that is never enforced is indistinguish-
    able from no constraint at all.
    """
    seen: set[str] = set()
    missing: list[str] = []

    def _check(mode):
        if mode is None or mode in seen:
            return
        seen.add(mode)
        if mode not in taxonomy:
            missing.append(mode)

    def _walk(steps: Iterable):
        for step in steps:
            _check(_attr(step, "start_mode"))
            _check(_attr(step, "goal_mode"))
            _check(_attr(step, "hold_mode"))
            branches = _attr(step, "branches")
            if branches:
                for branch in branches:
                    _walk(_attr(branch, "sub_plan"))

    _walk(_attr(plan, "steps"))
    for field in ("forbid_modes", "require_modes"):
        for mode in (_attr(plan, field) or ()):
            _check(mode)
    return missing


#: Modes you travel ALONG rather than pass THROUGH. A step may legally begin and
#: end in one of these — "follow the road and stop at the 2nd bench" never changes
#: mode, and generator.md teaches exactly that shape. Everything NOT listed here is
#: treated as a point you pass through, where X -> X means you never left.
#:
#: Every vocabulary we ship, so one rule serves the pedestrian rig and CARLA.
#: Matching is on the COLLAPSED form (see ``is_extent_mode``), so a spelling only
#: needs to appear here once: `path` covers `Path`, `open_space` covers
#: `Open Space`. The reordered campus spellings (`Space: Open`, `Edge: Along`) do
#: NOT collapse onto their siblings and are listed in their own right.
EXTENT_MODES: frozenset[str] = frozenset({
    "path", "along_edge", "passage", "open_space", "other",
    "Road: On", "Along Wall", "Passage", "Open Space",
    # cluster_map.combined.yaml / cluster_map.meadow_1hz.yaml
    "Corridor", "Covered", "Edge: Along", "Space: Open",
})


def is_extent_mode(mode: str | None) -> bool:
    """True for a mode you travel ALONG rather than pass THROUGH.

    Public because ``stl_syntax`` Rule 3b needs the same distinction: you are
    always inside an extent mode, so ``Detect(<extent mode>)`` can never mark a
    transition, while ``Detect(Junction)`` names a discrete place you approach
    and the cue oracle answers it.

    Compared on the collapsed form (alphanumerics, lower-cased): ``EXTENT_MODES``
    holds ``path`` but ``cluster_map.combined.yaml`` declares ``Path``, and an
    exact-string comparison would let ``Detect(Path)`` — the leak Rule 3b exists
    to catch — through on the campus taxonomy.
    """
    if not mode:
        return False
    if mode in EXTENT_MODES or _collapse_mode(mode) in _EXTENT_COLLAPSED:
        return True
    # Car-vocabulary phase modes ("Bridge: On", "Building: Past") name a stretch you
    # are on, not a point, so dwelling in one across a step is meaningful too.
    return mode.split(":")[0].strip() in {"Bridge", "Building"}


def _collapse_mode(mode: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "", mode).lower()


_EXTENT_COLLAPSED: frozenset[str] = frozenset(
    _collapse_mode(m) for m in EXTENT_MODES
)


#: Kept for callers that used the private spelling.
_is_extent_mode = is_extent_mode


def validate_plan_transitions(plan) -> list[str]:
    """Return every step whose mode transition cannot happen in one step.

    Two rules, both about the plan being TOPOLOGICALLY runnable rather than merely
    well-typed. ``validate_plan_modes`` checks each mode EXISTS; nothing checked
    that consecutive modes could follow one another, and a plan can satisfy every
    other validator and still describe a route no map affords.

    1. **A step must move — for POINT modes only.** ``X -> X`` is illegal when X is
       something you pass THROUGH (a junction) and legal when X is something you
       travel ALONG (a path, a wall, a passage, an open space).

       This distinction is load-bearing. Banning every ``X -> X`` also bans
       ``path -> path`` with ``cue_ordinal``, which is the encoding ``generator.md``
       Examples 4 and 5 explicitly teach for "stop at the 2nd bench": the robot is on
       the road before the bench and on the road after it, so there is no mode change
       and emitting one would stall the plan. An over-strict rule would also force
       ``path -> junction`` and so hide routing gaps in ``StepTargeter`` behind a
       rejected-but-correct plan.

    2. **Consecutive steps must chain.** Step N's ``goal_mode`` is where the robot
       is when step N+1 begins, so step N+1's ``start_mode`` must equal it.

    Rule 1 is what catches the `junction -> junction` failure. ``generator.md``
    forbids it in bold — a traversal must RETURN to `path` before the next one
    starts, because otherwise "three junctions" describes one junction you never
    leave — and the generator can emit it anyway. Such a plan passes schema
    validation, mode validation and the STL syntax check, but fails at routing
    ("no 'junction' adjacent to ...; plan and map disagree").

    Deliberately taxonomy-FREE, so it applies to any environment: it is a
    statement about the plan's own internal consistency, not about which clusters
    exist. Lives here beside ``validate_plan_modes`` so ``pipeline`` can feed both
    failures back to the generator the same way.
    """
    errs: list[str] = []

    def _walk(steps, where: str):
        nonlocal errs
        prev_goal = None
        for i, step in enumerate(steps or []):
            sm = _attr(step, "start_mode")
            gm = _attr(step, "goal_mode")
            branches = _attr(step, "branches")
            desc = (_attr(step, "description") or "")[:48]
            # A dwell step (`hold_mode` set) is `X -> X` BY CONSTRUCTION: it has
            # no destination, so there is nothing for it to end somewhere else.
            # Exempted the same way `branches` and the extent modes are — the
            # rule is "a step that claims to travel must move", and a dwell step
            # never claimed to. Without this, "hold the road until you see the
            # intersection" is rejected as "you never left the one you are in",
            # which is precisely what it is supposed to say.
            hold = _attr(step, "hold_mode")
            if sm == gm and not branches and not hold and not _is_extent_mode(sm):
                errs.append(
                    f"{where}[{i}] ({desc!r}): start_mode == goal_mode == {sm!r}. "
                    f"{sm!r} is something you pass THROUGH, so {sm!r} -> {sm!r} reads "
                    f"as never leaving the one you are already in. To traverse "
                    f"another, return to the connecting mode first: "
                    f"path -> junction, junction -> path, path -> junction. "
                    f"(Staying in the same mode IS legal for path / along_edge / "
                    f"passage / open_space — that is how 'stop at the 2nd bench' "
                    f"is written.)"
                )
            if prev_goal is not None and sm != prev_goal:
                errs.append(
                    f"{where}[{i}] ({desc!r}): start_mode {sm!r} does not continue "
                    f"from the previous step's goal_mode {prev_goal!r}. Steps run "
                    f"back to back, so step N+1 starts where step N ended."
                )
            prev_goal = gm
            if branches:
                for b_i, b in enumerate(branches):
                    sub = _attr(b, "sub_plan")
                    cue = _attr(b, "vlm_cue")
                    _walk(sub, f"{where}[{i}].branches[{b_i}] ({cue!r})")

    _walk(_attr(plan, "steps"), "steps")
    return errs


#: Nouns that name a PLACE the robot enters, not an object it sights. Arrival at one of
#: these is a cluster transition, so it belongs to the topology channel and not to the
#: visual one.
_PLACE_NOUNS = ("intersection", "junction", "crossroad", "crossroads", "four-way",
                "fourway", "roundabout", "corner")


def repair_place_detect_to_traverse(plan) -> list[str]:
    """Turn ``Detect(<place>)`` on a place-mode step into a cluster traversal. What it did.

    WHY. The system has two perception channels and they do different jobs:

      * the CLUSTER channel (LiDAR region classifier) reports which region the robot is
        in. It drives step advancement and gives the MPC its target. Progress is measured
        here.
      * the VISUAL channel (`Detect(...)`, answered by the VLM or the ground-truth oracle)
        answers DECISIONS. It picks a branch; it does not measure progress.

    "Approach the first crossroads" names a place, so arrival is a cluster transition --
    `goal_mode: junction` with `trigger: traverse`. The prompt says to use `landmark`
    "whenever the English names a thing to see", which mis-files every place noun into the
    visual channel, and the step then waits for a SIGHTING of something the region
    classifier already knows the robot is standing in.

    Example: ``transition_cue: Detect(Crossroads)`` on step 0 means brain never advances
    past step 0, even when every cue answer is correct.

    DETERMINISTIC AND SOUND: the step keeps its `goal_mode`, so where it ends is unchanged;
    only the evidence changes, from a sighting nothing publishes to the cluster arrival the
    classifier already reports. Branch `vlm_cue`s are untouched -- those ARE decisions, and
    naming a place inside one is legitimate (see the conjunctive matcher).
    """
    fixed: list[str] = []

    def walk(steps, where=""):
        for st in steps or []:
            if not isinstance(st, dict):
                continue
            cue = str(st.get("transition_cue") or "")
            m = re.match(r"\s*detect\(([^)]*)\)", cue, re.I)
            goal = str(st.get("goal_mode") or "").lower()
            if m and any(n in m.group(1).lower() for n in _PLACE_NOUNS) \
                    and any(n in goal for n in _PLACE_NOUNS):
                st["transition_cue"] = None
                st["trigger"] = "traverse"
                fixed.append(f"{where}step {st.get('step')}: {cue!r} on a {goal!r} step "
                             f"-> trigger 'traverse' (arrival is a cluster transition, "
                             f"not a sighting)")
            for i, b in enumerate(st.get("branches") or []):
                if isinstance(b, dict):
                    walk(b.get("sub_plan") or [], f"{where}br{i}/")

    if isinstance(plan, dict):
        walk(plan.get("steps") or [])
    return fixed


#: Modes you are INSIDE for the whole step, as token sets. `Detect(Path)` asks a question
#: whose answer is always yes, so the step can never advance (a deadlock).
#: `junction` is deliberately absent: you APPROACH a
#: junction, so `Detect(Junction)` is legitimate and `repair_place_detect_to_traverse`
#: owns that case.
_MEDIUM_MODES = (frozenset({"path"}), frozenset({"passage"}), frozenset({"road"}),
                 frozenset({"open", "space"}), frozenset({"edge", "along"}),
                 frozenset({"wall", "along"}))

_TURN_CUE = re.compile(r"\s*detect\(\s*(left|right|straight)\s*turn\s*\)\s*$", re.I)


def _mode_tokens(name) -> frozenset:
    """`"Edge: Along"`, `"AlongEdge"` and `"along_edge"` all -> {along, edge}."""
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", str(name or ""))
    return frozenset(w for w in re.split(r"[^A-Za-z0-9]+", s.lower()) if w)


def repair_medium_detect_cue(plan) -> list[str]:
    """Fix a `transition_cue` that asks to SEE the medium, or to see a turn. What it did.

    Two shapes are repaired. They are the unanswerable cues caused by the prompt's own
    encoding; most other unanswerable cues name referents this deployment has no family
    for at all, which are not repairable here and are left for the gate to report.

      1. `Detect(<medium>)` ENTERING that medium -- `Detect(Path)` on an `Other -> Path`
         step, `Detect(Passage)` on a `Path -> Passage` step. The evidence
         it wants is a cluster arrival the region classifier already publishes, so this
         becomes `trigger: traverse` with no cue. Exactly the argument
         `repair_place_detect_to_traverse` makes for place nouns, and sound for the same
         reason: `goal_mode` is untouched, so WHERE the step ends does not change -- only
         what counts as having got there.

      2. `Detect(RightTurn)` -- a MANOEUVRE written as an object, typically on a step
         whose `start_mode` equals its `goal_mode` (`Path -> Path`,
         `Edge: Along -> Edge: Along`). Becomes `Bearing(Right) completed` with
         `trigger: topology`, which is what the prompt's own verb table prescribes and
         what example 1 of `generator_v5.md` already demonstrates. `Bearing(...)` is
         resolved from the trajectory, so `cue_vocab._TRAJECTORY_CUE` exempts it and it is
         answerable by construction.

    WHY RULE 1 REQUIRES `start_mode != goal_mode` AND A NAME MATCH. Turning a cue into
    `traverse` is only sound when a cluster transition actually happens. On a `Path ->
    Path` step there is none, so `traverse` would either complete instantly or never --
    a semantics change, not a repair. A `Detect(Passage)` on a `Path -> Path` step is
    left alone for precisely this reason; the gate reports it and the model retries.

    BRANCH STEPS ARE SKIPPED. A step with `branches` asks its question through the branch
    cues (`repair_prose_decision_cue` owns that); these shapes occur on `transition_cue`.
    Scoping keeps a decision step's evidence out of this function.
    """
    fixed: list[str] = []

    def walk(steps, where=""):
        for st in steps or []:
            if not isinstance(st, dict):
                continue
            for i, b in enumerate(st.get("branches") or []):
                if isinstance(b, dict):
                    walk(b.get("sub_plan") or [], f"{where}br{i}/")
            if st.get("branches"):
                continue
            cue = str(st.get("transition_cue") or "")
            if not cue:
                continue

            turn = _TURN_CUE.match(cue)
            if turn:
                d = turn.group(1).capitalize()
                st["transition_cue"] = f"Bearing({d}) completed"
                st["trigger"] = "topology"
                fixed.append(f"{where}step {st.get('step')}: {cue!r} is a manoeuvre, not "
                             f"an object -> 'Bearing({d}) completed' / trigger 'topology'")
                continue

            m = re.match(r"\s*detect\(([^)]*)\)\s*$", cue, re.I)
            if not m:
                continue
            named = _mode_tokens(m.group(1))
            goal = _mode_tokens(st.get("goal_mode"))
            start = _mode_tokens(st.get("start_mode"))
            if named and named in _MEDIUM_MODES and named == goal and start != goal:
                st["transition_cue"] = None
                st["trigger"] = "traverse"
                fixed.append(
                    f"{where}step {st.get('step')}: {cue!r} asks to SEE the medium it is "
                    f"entering -> trigger 'traverse' (arrival at {st.get('goal_mode')!r} "
                    f"from {st.get('start_mode')!r} is a cluster transition)")

    if isinstance(plan, dict):
        walk(plan.get("steps") or [])
    return fixed


def repair_prose_decision_cue(plan) -> list[str]:
    """Null out a prose ``transition_cue`` on a step that has branches. Returns what it did.

    DETERMINISTIC AND SOUND, and it is the fix ``validate_decision_cues`` already names in
    its own error text: "Either set transition_cue to null and let the branches decide".
    There is exactly one repair and it needs no model.

    Sound because the branches carry the perception question. A decision step's own cue is
    redundant when it is a real predicate and unanswerable when it is prose -- "decision
    point" is not something any publisher can answer, so the step never completes even when
    a branch resolves correctly, and the robot drives past its target until the cue budget
    kills the run.

    WHY IT EXISTS. On deep (depth-3) missions this is a common failure, typically with
    the literal string `"decision point"`. Re-prompting re-rolls a correct plan to delete
    one field.

    Operates on a RAW dict, before validation, beside repair_degenerate_branches.
    """
    fixed: list[str] = []

    def walk(steps, where=""):
        for st in steps or []:
            if not isinstance(st, dict):
                continue
            br = st.get("branches")
            cue = st.get("transition_cue")
            if br and cue:
                low = str(cue).lower()
                if "detect(" not in low and "bearing(" not in low:
                    st["transition_cue"] = None
                    fixed.append(f"{where}step {st.get('step')}: dropped prose cue {cue!r} "
                                 f"from a branching step")
            for i, b in enumerate(br or []):
                if isinstance(b, dict):
                    walk(b.get("sub_plan") or [], f"{where}br{i}/")

    if isinstance(plan, dict):
        walk(plan.get("steps") or [])
    return fixed


def repair_degenerate_branches(plan) -> list[str]:
    """Splice out decision steps whose ONLY branch is ``default``. Returns what it did.

    DETERMINISTIC AND SOUND, because a decision step with one branch is not a decision.
    The schema already refuses it (``branches must have >= 2 entries``); this removes the
    wrapper and puts the branch's own steps in its place, which is what the step meant.

    WHY IT EXISTS. On deep (depth-3) missions the model tends to fail this rule at a
    consistent structural position, while NOT getting the deep decision wrong -- the real
    third-level decision underneath is correctly formed with its cue branch and default:

        sub[2].br[0].sub[0]  decision: 1 branch ['default']      <- null wrapper
            sub[0] plain: Approach the third junction
            sub[1] decision: 2 branches ['cone present', 'default']   <- correct

    It wraps the *continuation* of a branch in a pointless default-only decision. The plan
    is right and the shape is wrong, so re-prompting re-rolls a correct plan to fix a
    structural tic. This edits the shape and leaves the content untouched -- the same
    argument that justifies ``repair_cue_ordinal``.

    Operates on a RAW dict, before validation, because this failure kills the model_validate
    call that ``repair_cue_ordinal`` runs after.
    """
    fixed: list[str] = []

    def only_default(step) -> bool:
        br = step.get("branches")
        if not isinstance(br, list) or len(br) != 1:
            return False
        cue = (br[0].get("vlm_cue") or "").strip().lower()
        return cue == "default"

    def splice(steps, where=""):
        if not isinstance(steps, list):
            return steps
        out = []
        for st in steps:
            if not isinstance(st, dict):
                out.append(st)
                continue
            if only_default(st):
                inner = splice(st["branches"][0].get("sub_plan") or [], where)
                fixed.append(f"{where}step {st.get('step')}: default-only decision spliced "
                             f"({len(inner)} step(s) lifted)")
                out.extend(inner)
                continue
            if isinstance(st.get("branches"), list):
                for i, b in enumerate(st["branches"]):
                    if isinstance(b, dict):
                        b["sub_plan"] = splice(b.get("sub_plan") or [],
                                               f"{where}br{i}/")
            out.append(st)
        # step indices are 0-based WITHIN their list, so renumber after any splice
        for i, st in enumerate(out):
            if isinstance(st, dict) and "step" in st:
                st["step"] = i
        return out

    if isinstance(plan, dict):
        plan["steps"] = splice(plan.get("steps") or [])
    return fixed


def repair_cue_ordinal(plan) -> list[str]:
    """Strip the redundant ``cue_ordinal`` from double-counted steps. Returns what it did.

    DETERMINISTIC, and sound for the reason ``validate_cue_ordinal`` gives: when a plan
    already contains two or more steps ending in the same POINT mode, the count lives in
    the step index and a ``cue_ordinal`` on any of them "is redundant". Redundant is not
    ambiguous -- there is exactly one repair, and it needs no model.

    Worth doing rather than re-prompting: this validator is a leading cause of
    non-convergence. A retry re-rolls the whole plan and may lose parts that were already
    right; this edits one field and leaves everything else untouched.

    Landmark counting is untouched, exactly as in the validator -- a landmark plan has one
    such step, not several.
    """
    fixed: list[str] = []

    def walk(steps, where=""):
        by_mode: dict[str, list] = {}
        for st in steps or []:
            if not isinstance(st, dict):
                continue
            gm = st.get("goal_mode")
            if gm and not is_extent_mode(gm):
                by_mode.setdefault(gm, []).append(st)
        for mode, group in by_mode.items():
            if len(group) < 2:
                continue                      # one step: a landmark count, leave it
            for st in group:
                if st.get("cue_ordinal"):
                    fixed.append(
                        f"{where}steps[{st.get('step')}]: dropped cue_ordinal="
                        f"{st['cue_ordinal']} -- {mode!r} is unrolled across "
                        f"{len(group)} steps, so the index already carries the count")
                    st["cue_ordinal"] = None
        for i, st in enumerate(steps or []):
            for b in ((st or {}).get("branches") or []):
                walk(b.get("sub_plan"), f"{where}steps[{i}].branch.")

    walk(plan.get("steps") if isinstance(plan, dict) else
         getattr(plan, "steps", None) and
         __import__("json").loads(plan.model_dump_json())["steps"])
    return fixed


def validate_cue_ordinal(plan) -> list[str]:
    """Return every step that DOUBLE-COUNTS an unrolled traversal.

    Fourth site of the same disease as ``validate_decision_cues``: the prompt states a
    rule, nothing enforces it, and the model breaks it. ``generator.md`` is explicit --

        Counting TRAVERSALS (intersections) -> UNROLL. Every unrolled step must have
        cue_ordinal: null; the step index already encodes "second". Setting
        cue_ordinal on an unrolled step DOUBLE-COUNTS: the robot would sit in that
        step waiting to see two MORE intersections.

        Counting LANDMARK SIGHTINGS (benches, doors) -> ONE step, cue_ordinal: N.

    The model frequently unrolls correctly AND stamps ``cue_ordinal`` anyway on
    intersection-counting plans. The error is silent -- the plan passes modes,
    transitions and cues, and would drive to the 5th intersection when asked for the 3rd.

    **The rule, and why it is decidable.** A point mode (``junction``) is something you
    pass THROUGH, so N of them means N steps. An extent mode (``path``) is something you
    travel ALONG, so "the 2nd bench" is one ``path -> path`` step carrying
    ``cue_ordinal: 2``. The two encodings are therefore distinguishable without knowing
    what is being counted: if a plan already contains two or more steps ending in the
    same point mode, the count is in the step INDEX, and a ``cue_ordinal`` on any of
    them is redundant. Landmark counting is untouched, because a landmark plan has one
    such step, not several.

    Taxonomy-free like its neighbours -- a statement about the plan's own consistency.
    """
    errs: list[str] = []
    unrolled: dict[str, int] = {}
    carriers: list[tuple[str, int, str, int]] = []

    def _walk(steps, where: str):
        for i, step in enumerate(steps or []):
            gm = _attr(step, "goal_mode")
            ordinal = _attr(step, "cue_ordinal")
            if gm and not is_extent_mode(gm):
                unrolled[gm] = unrolled.get(gm, 0) + 1
                if ordinal:
                    carriers.append((where, i, gm, int(ordinal)))
            for br in (_attr(step, "branches") or ()):
                _walk(_attr(br, "sub_plan"), f"{where}[{i}].branch")

    _walk(_attr(plan, "steps"), "steps")
    for where, i, gm, ordinal in carriers:
        if unrolled.get(gm, 0) >= 2:
            errs.append(
                f"{where}[{i}]: goal_mode {gm!r} appears in {unrolled[gm]} steps AND this "
                f"step sets cue_ordinal={ordinal}. That double-counts -- the step index "
                f"already encodes the ordinal, so the robot would wait for {ordinal} MORE "
                f"{gm}s. Unroll OR use cue_ordinal, never both (generator.md: 'NEVER do "
                f"both for the same count')."
            )
    return errs


def validate_decision_cues(plan) -> list[str]:
    """Return every branching step that also carries a predicate-free landmark cue.

    Third site of one disease: **an unanswerable cue on a step that gates
    advancement.** Rule 3b in ``stl_syntax`` closed the first (a mode name inside
    ``Detect(...)``). This is the second, and it evades 3b because it is not in the
    STL at all — it is the ``transition_cue`` JSON field. Example::

        step 2: path -> junction  trigger=landmark  transition_cue='decision point'
                branch 'cone is present in the junction' -> Bearing(Straight)
                branch 'default'                         -> Bearing(Right)

    The branches already carry the perception question; the step's own cue is prose
    describing what the step IS. The branch resolves correctly and drives to the right
    exit — and then the step never completes, so the vehicle keeps driving until the
    cue budget ends the run.

    **Why the rule is structural rather than a check on the cue text.**
    ``transition_cue`` is free text BY DESIGN (``schemas.PlanStep``: brain's VLM polls
    it) and ``schemas.infer_trigger`` deliberately maps free text to ``landmark``. So
    "is this cue answerable" is not decidable — ``"a light brown bench"`` is a
    legitimate pedestrian cue and ``"decision point"`` is not, and nothing in the
    string tells them apart. What IS decidable is the redundancy: a step whose
    branches ask the question does not need to ask it again, and if it does ask, the
    ask must be a predicate something can answer.

    Scoped to branching steps on purpose. A predicate-free cue on a plain step is the
    documented pedestrian shape and is left alone.

    Taxonomy-free, like ``validate_plan_transitions`` — a statement about the plan's
    own consistency, so it serves any environment.
    """
    errs: list[str] = []

    def _walk(steps, where: str):
        for i, step in enumerate(steps or []):
            branches = _attr(step, "branches")
            cue = (_attr(step, "transition_cue") or "").strip()
            if branches and cue:
                low = cue.lower()
                # `Bearing(Right) completed` counts as a predicate — the trailing
                # prose is harmless and the maneuver extraction reads it by substring.
                if "detect(" not in low and "bearing(" not in low:
                    desc = (_attr(step, "description") or "")[:48]
                    cues = [(_attr(b, "vlm_cue") or "") for b in branches]
                    errs.append(
                        f"{where}[{i}] ({desc!r}): transition_cue {cue!r} is prose, not "
                        f"a Detect(...) / Bearing(...) predicate, on a step that also "
                        f"has branches {cues}. Nothing can answer it, so the step never "
                        f"completes even when a branch resolves correctly — the robot "
                        f"drives past its target until the cue budget kills the run. "
                        f"The branches already carry the perception question. Either "
                        f"set transition_cue to null and let the branches decide, or "
                        f"make it a real predicate for the thing that marks arrival "
                        f"(e.g. Detect(Intersection)). Do not describe the step."
                    )
            if branches:
                for b_i, b in enumerate(branches):
                    _walk(_attr(b, "sub_plan"),
                          f"{where}[{i}].branches[{b_i}] ({_attr(b, 'vlm_cue')!r})")

    _walk(_attr(plan, "steps"), "steps")
    return errs


def _attr(obj, name: str):
    if isinstance(obj, dict):
        return obj.get(name)
    return getattr(obj, name, None)


__all__ = [
    "ClusterTaxonomy",
    "TaxonomyError",
    "load_taxonomy",
    "validate_plan_modes",
    "validate_plan_transitions",
    "validate_decision_cues",
    "validate_cue_ordinal",
    "repair_cue_ordinal",
    "repair_degenerate_branches",
    "repair_prose_decision_cue",
    "repair_place_detect_to_traverse",
    "EXTENT_MODES",
    "is_extent_mode",
]
