"""Phase A: run a mission with ground-truth perception and no sensors.

    ros2 launch carla_gt_bridge mission.launch.py plan_file:=<tree.json> role_name:=ego_vehicle

The CARLA server and `carla_ros_bridge` are started separately. The core nodes are:

    gt_cluster_node   /carla/<role>/odometry  -> /predicted_cluster
    gt_cue_node       actor list + cluster    -> /cue/confirmations
    brain_controller  /predicted_cluster      -> /brain/state
    carla_mpc_node    /brain/state + odometry -> /carla/<role>/twist
    load_mission_node <plan_file>             -> /brain/incoming_plan (latched, held)

plus `lidar_ranges_node`, and optionally `cluster_space_guard` and `terrain_mask_node`.

``role_name`` is a launch argument rather than a constant because the bridge's default
and this repo's hardcoded value disagree (`hero` vs `ego_vehicle`), and every topic name
depends on it. Check with `ros2 topic list | grep carla` before the first run: if the
prefix is wrong, nothing is published where these nodes look and the failure reads as
"the MPC never moved".

Phase A deliberately has no VLM:

* cues are answered from ground truth by ``gt_cue_node`` (``cue_source`` = topic).
* ``require_ranges:=false`` — with ``no_rendering_mode`` on there are no cameras; the
  LiDAR scan (a physics raycast) is consumed when present, but a missing scan degrades
  rather than blocking the ground-truth phase.
"""

import os


def _envf(name: str, default: float) -> float:
    """float() an env var, treating EMPTY as unset.

    `docker exec -e VAR=${VAR:-}` forwards the variable as an EMPTY STRING when the host
    has not set it, so `os.environ.get(name, default)` returns "" rather than the default
    and `float("")` kills the whole launch with
    `ValueError: could not convert string to float: ''` -- which names nothing and looks
    like a syntax error in the launch file.
    """
    raw = os.environ.get(name, "")
    try:
        return float(raw) if str(raw).strip() else float(default)
    except ValueError:
        return float(default)


def _envb(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name, "").strip().lower()
    return default if not raw else raw in ("1", "true", "yes", "on")


from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, TimerAction
from launch.conditions import LaunchConfigurationNotEquals
from launch.substitutions import (LaunchConfiguration, PathJoinSubstitution,
                                  TextSubstitution)
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare

CFG = PathJoinSubstitution([FindPackageShare("carla_gt_bridge"), "config"])


def generate_launch_description() -> LaunchDescription:
    role = LaunchConfiguration("role_name")
    town = LaunchConfiguration("town")

    args = [
        DeclareLaunchArgument("role_name", default_value="ego_vehicle",
                              description="bridge topic prefix: /carla/<role_name>/..."),
        # The brain tree to drive (required), e.g. generated by drive_english.py.
        DeclareLaunchArgument("plan_file", default_value="",
                              description="path to a brain tree JSON (required)"),
        DeclareLaunchArgument("town", default_value="town05"),
        # "region" | "centroid". Exposed so the two can be compared without a code edit.
        # The node and this launch file both default to "centroid"; run_phase_a.sh passes
        # "region" (its GUIDANCE default).
        DeclareLaunchArgument("guidance", default_value="centroid",
                              description="MPC steering signal: region | centroid"),
        # EDT rejection distance. The most consequential number at a junction: too large
        # and it rejects most of the rollouts there, leaving the vehicle unable to turn.
        DeclareLaunchArgument("safety_radius", default_value="1.5",
                              description="metres; rollouts passing this close to a "
                                          "LiDAR hit are removed from consideration"),
        # How many of the N horizon steps the collision test looks at. The test is
        # `.any()` over the WHOLE 1.6 s horizon, so a rollout dies because its 8th step
        # -- the least trustworthy prediction it makes -- clips a pole it would have
        # replanned around four ticks earlier. 0 means all N (the original behaviour).
        # >=0 seeds the MPC sampler and the run replays exactly; <0 is OS entropy.
        # Set this to the repeat index when repeating runs: repeats stay different from
        # one another, and any single run can be replayed.
        DeclareLaunchArgument("mpc_seed", default_value="0",
                              description="MPC sampler seed; <0 for OS entropy"),
        # Map distortion, applied to centroids and bearings only. See the node's
        # `_apply_distortion` for why membership is deliberately left true.
        DeclareLaunchArgument("aim_source", default_value="region"),
        # Which controller drives. "region" is the default; "terrain" is the
        # curvature-fan controller that never asks which region a FUTURE position
        # belongs to.
        DeclareLaunchArgument("controller", default_value="region"),
        DeclareLaunchArgument("kappa_max", default_value="0.25"),
        # WHERE THE TERRAIN LABELS COME FROM. "waypoint" is the CARLA ground-truth stand-in
        # and stays the default; "camera" consumes `/terrain/class_mask` from
        # `terrain_mask_node`, which is the
        # only one of the two a robot can have. `terrain_labeller` picks what produces that
        # mask -- carla_semantic (an oracle, like gt_cluster_node), segformer or hsv.
        # The id space consumers expect on /predicted_cluster, e.g.
        # "region:carla_town05". Empty (the default) leaves the guard out; set it to turn
        # the check on.
        DeclareLaunchArgument("cluster_space", default_value=""),
        DeclareLaunchArgument("terrain_source", default_value="waypoint"),
        DeclareLaunchArgument("terrain_labeller", default_value="carla_semantic"),
        DeclareLaunchArgument("forbid_terrain", default_value=""),
        DeclareLaunchArgument("terrain_decay_m", default_value="0.0"),
        # Fan overlays every N control ticks, into <log dir>/terrain_overlays. 0 = off, the
        # default: 65 arcs x 200 samples x 2 panels is not something to do every tick.
        DeclareLaunchArgument("overlay_every_n", default_value="0"),
        # Camera geometry, ONE declaration feeding BOTH the mask node and the MPC. Two
        # separate expressions of the same geometry drift apart silently, e.g. projecting
        # 130/30 frames through a 110/0 model reports blind arcs that do not exist.
        DeclareLaunchArgument("cam_x", default_value="2.425"),
        DeclareLaunchArgument("cam_z", default_value="1.5"),
        DeclareLaunchArgument("cam_fov", default_value="130.0"),
        DeclareLaunchArgument("cam_pitch_down_deg", default_value="30.0"),
        DeclareLaunchArgument("arc_len_m", default_value="10.0"),
        DeclareLaunchArgument("fan_size", default_value="65"),
        # 1 = the shipped single-arc fan; 2 = the two-segment grid. Default unchanged.
        DeclareLaunchArgument("fan_segments", default_value="1"),
        # Graded obstacle penalty for the REGION controller. 0.0 = shipped behaviour.
        DeclareLaunchArgument("w_obstacle", default_value="0.0"),
        DeclareLaunchArgument("pure_pursuit", default_value="false"),
        DeclareLaunchArgument("distortion_model", default_value="similarity"),
        DeclareLaunchArgument("distortion_jitter_frac", default_value="0.0"),
        # Displace the DRIVABLE SURFACE by the same per-region offsets as the centroids,
        # so cluster membership and the goal point both read a wrong map. Off by default:
        # the waypoint table is left undistorted.
        DeclareLaunchArgument("distortion_surface", default_value="false"),
        # Per-region displacement in METRES (overrides the fraction) and per-region
        # rotation in degrees. Metres because 7 m is directly comparable to the 7.0 m
        # road half-width; the fraction form is not.
        DeclareLaunchArgument("distortion_jitter_m", default_value="0.0"),
        DeclareLaunchArgument("distortion_region_rot_deg", default_value="0.0"),
        DeclareLaunchArgument("distortion_pivot", default_value="map"),
        DeclareLaunchArgument("distortion_angle_deg", default_value="0.0"),
        DeclareLaunchArgument("distortion_scale", default_value="1.0"),
        DeclareLaunchArgument("distortion_tx", default_value="0.0"),
        DeclareLaunchArgument("distortion_ty", default_value="0.0"),
        DeclareLaunchArgument("collision_horizon", default_value="0",
                              description="steps of the horizon to collision-check; "
                                          "0 = all N"),
        # Speed cap while brain is DECIDING, so the vehicle does not leave the decision
        # junction before the branch commits. Declared here as well as on the node so it
        # can be tuned without editing the node.
        DeclareLaunchArgument("decide_v_max",
                              default_value=str(_envf("DECIDE_V_MAX", 1.0)),
                              description="m/s cap while brain_state == DECIDING"),
        DeclareLaunchArgument("v_max", default_value="5.0",
                              description="m/s; the old node's 1.0 was walking pace"),
        DeclareLaunchArgument("cone_regions", default_value="",
                              description="regions where cones were spawned, e.g. [66,53]; "
                                          "empty derives from the actor list"),
        DeclareLaunchArgument("force_cone", default_value="auto",
                              choices=["auto", "present", "absent"],
                              description="assert the cone cue instead of reading the "
                                          "actor list; 'auto' is the real path"),
        DeclareLaunchArgument("dry_run", default_value="false",
                              description="compute and log commands but publish no Twist"),
        # THE WALL-CLOCK LEVER. Under synchronous_mode + wait_for_vehicle_control_command
        # the world advances only when the MPC produces a command, so sim time is gated
        # on how long one control tick takes.
        #
        # K is the rollout count and dominates the per-tick cost. Lower K trades path
        # quality for wall clock; measure before trusting a value, since too few rollouts
        # shows up as a worse path rather than as an error.
        # Experimental: publish cue answers place-key-first, the ordering that made an
        # ambiguous branch cue answer the wrong predicate. Default false.
        DeclareLaunchArgument("cue_place_first", default_value="false"),
        DeclareLaunchArgument("mpc_K", default_value="500",
                              description="MPC rollouts per tick; the dominant wall-clock "
                                          "cost under wait-for-control"),
        DeclareLaunchArgument("mpc_N", default_value="8",
                              description="MPC horizon steps"),
        # 1, not dt/fixed_delta=4. Under wait-for-control the server holds each world
        # tick until it gets a control command, so any tick this node does not service
        # stalls on a ~1 s timeout, so n>1 runs far slower than real time.
        DeclareLaunchArgument("control_every_n_odom", default_value="1",
                              description="odometry messages per control tick; 1 is "
                                          "required under wait-for-control"),
    ]

    odom = ["/carla/", role, "/odometry"]
    regions = PathJoinSubstitution([CFG, ["regions.", town, ".npz"]])

    # SIMULATED time, on every node. The bridge in synchronous mode ticks the world as
    # fast as it can (several times wall clock), so a controller on a wall-clock timer
    # issues commands too rarely in simulated time and is effectively open-loop between
    # them; a straight road may survive that, a turn will not. With use_sim_time the
    # MPC's dt=0.2 means 0.2 SIMULATED seconds, so the control rate tracks the world
    # rather than the host.
    #
    # `-fps N` on the server throttles RENDERING, not ticking, so it does not help here.
    SIM_TIME = {"use_sim_time": True}

    gt_cluster = Node(
        package="carla_gt_bridge", executable="gt_cluster_node",
        name="gt_cluster_node", output="screen",
        parameters=[{"regions_npz": regions, "odom_topic": odom}, SIM_TIME])

    # WHAT THE INTEGER ON /predicted_cluster MEANS, asserted rather than assumed.
    # Five live nodes publish that topic and the value is a region id here, an HDBSCAN
    # cluster id in `clustering/`, and a label index in `bev_pipeline/`. They are
    # indistinguishable on the wire, so a consumer holding the wrong cluster_map resolves
    # every id to the wrong mode and drives somewhere plausible for the wrong reason.
    # The guard also catches two producers racing, and the subtler case of the same town
    # with a DIFFERENT id set (two region tables of different sizes that both call
    # themselves `carla_town01`). The guard runs only when `cluster_space` is set; pass it
    # explicitly, especially when a perception producer replaces the oracle.
    cluster_guard = Node(
        package="carla_gt_bridge", executable="cluster_space_guard",
        name="cluster_space_guard", output="screen",
        condition=LaunchConfigurationNotEquals("cluster_space", ""),
        parameters=[{"expect": LaunchConfiguration("cluster_space")}, SIM_TIME])

    # The mask node runs only for the camera terrain source. It is a perception stand-in
    # publishing on the topic the real stack uses, as gt_cluster_node and gt_cue_node are -- and
    # like them it is NOT a perception result when its labeller is `carla_semantic`.
    terrain_mask = Node(
        package="carla_gt_bridge", executable="terrain_mask_node",
        name="terrain_mask_node", output="screen",
        condition=LaunchConfigurationNotEquals("terrain_source", "waypoint"),
        parameters=[{"labeller": LaunchConfiguration("terrain_labeller"),
                     "odom_topic": odom,
                     "cam_x": ParameterValue(LaunchConfiguration("cam_x"), value_type=float),
                     "cam_z": ParameterValue(LaunchConfiguration("cam_z"), value_type=float),
                     "fov": ParameterValue(LaunchConfiguration("cam_fov"), value_type=float),
                     "pitch_down_deg": ParameterValue(
                         LaunchConfiguration("cam_pitch_down_deg"), value_type=float)},
                    SIM_TIME])

    brain = Node(
        package="brain", executable="brain_controller",
        name="brain_controller", output="screen",
        # brain reads yaw from /odom, so point it at the bridge's odometry rather than
        # remapping — a remap would also catch any other /odom publisher.
        parameters=[{"odom_topic": odom, "traverse_dwell_frames": 3,
                     "bearing_complete_deg": 60.0,
                     # Distance bound on a Bearing(...) manoeuvre. Without it the check
                     # certifies turns that never happened: 60 deg of heading can build
                     # up over ~150 m of route curvature while the vehicle drives
                     # straight through the junction. Env-overridable; 0 = unbounded.
                     "bearing_scope_m": _envf("BEARING_SCOPE_M", 45.0),
                     # A turn completes as the vehicle EXITS the junction, so heading
                     # keeps accumulating for this far past the decision cluster.
                     "bearing_exit_grace_m": _envf("BEARING_EXIT_GRACE_M", 15.0),
                     # Scoped conjunction with sequential accumulation: ask "is there an X
                     # in the NEAREST intersection ahead?" on approach, seal the answer to
                     # the junction on entry. Default OFF -- it changes when cues confirm.
                     "cue_scoped_approach": _envb("CUE_SCOPED_APPROACH", False),
                     "cue_evidence_m": _envf("CUE_EVIDENCE_M", 12.0),
                     "cue_approach_every_m": _envf("CUE_APPROACH_EVERY_M", 8.0),
                     # ON here, off by default: without it `junction -> path` is
                     # satisfied without moving (a junction's id is inside `path` by
                     # subsumption), and the hard mission fires its branch at the FIRST
                     # junction. Off by default in brain for offline evaluation.
                     "require_cluster_change": True,
                     # Phase A has no camera (no_rendering_mode), so cues are answered
                     # from the simulator's own state by gt_cue_node. The seam changes
                     # only WHERE the boolean comes from; the ordinal de-bounce, the
                     # timeout and the branch pick are the same code either way.
                     "cue_source": os.environ.get("CUE_SOURCE", "topic"),
                     # legacy (default) | v2: scoped + windowed landmark counting (brain_controller.py)
                     "cue_semantics": os.environ.get("CUE_SEMANTICS", "") or "legacy",
                     "cue_timeout_s": 30.0}, SIM_TIME])

    # BRAIN_MODE=llm replaces the plan-tree brain with an LLM that decides at every
    # region change from the same ground-truth cluster/cue topics and publishes the same /brain/state.
    # Default (unset) is the plan-tree brain, unchanged. See carla_gt_bridge/nodes/llm_brain_node.py.
    llm_mode = os.environ.get("BRAIN_MODE", "").strip().lower() == "llm"
    if llm_mode:
        brain = ExecuteProcess(
            cmd=["python3", os.environ.get("LLM_BRAIN_SCRIPT", "")          # forwarded ${VAR:-} is "" -> use `or`
                 or "/ros_ws/src/carla_gt_bridge/carla_gt_bridge/nodes/llm_brain_node.py",
                 "--ros-args", "-p", "use_sim_time:=true"],
            output="screen", name="llm_brain")

    # LIDAR -> the 360-bin scan the MPC's obstacle EDT consumes. Without it `_hits_body`
    # returns None, no rollout is ever rejected, and the planner drives into buildings that
    # appear in neither the .xodr nor /carla/actor_list. `require_ranges` stays False so a
    # missing scan degrades instead of hanging -- the ground-truth phase must still run if
    # the sensor is ever absent.
    lidar_ranges = Node(
        package="carla_gt_bridge", executable="lidar_ranges_node",
        name="lidar_ranges_node", output="screen",
        parameters=[{"cloud_topic": ["/carla/", role, "/lidar"]}, SIM_TIME],
    )

    gt_cue = Node(
        package="carla_gt_bridge", executable="gt_cue_node",
        name="gt_cue_node", output="screen",
        parameters=[{"regions_npz": regions, "odom_topic": odom,
                     # Passed EXPLICITLY rather than derived from __file__: with
                     # --symlink-install the installed module sits outside the package's
                     # config dir, so a path guessed from __file__ resolves to nothing and
                     # the family map comes back EMPTY -- which reads as "no bench in this
                     # world" rather than as a broken lookup.
                     "prop_tables": ParameterValue(
                         [PathJoinSubstitution([CFG, ["cones.", town, ".json"]]),
                          TextSubstitution(text=","),
                          PathJoinSubstitution([CFG, ["props.", town, ".json"]])],
                         value_type=str),
                     "force_cone": LaunchConfiguration("force_cone"),
                     # value_type=str is required: launch INFERS types, so a bare
                     # "66" arrives as an integer and clashes with the string default,
                     # killing the node at startup ("66,53" works only because the
                     # comma makes it non-numeric).
                     "cone_regions": ParameterValue(
                         LaunchConfiguration("cone_regions"), value_type=str),
                     "cue_place_first": ParameterValue(
                         LaunchConfiguration("cue_place_first"), value_type=bool),
                     # per-world ground-truth landmarks, e.g. EXTRA_LANDMARKS="stop_sign:63,59"
                     "extra_landmarks": ParameterValue(
                         os.environ.get("EXTRA_LANDMARKS", ""), value_type=str)},
                    SIM_TIME])

    mpc = Node(
        package="dgppo_ros_node_pkg", executable="carla_mpc_node",
        name="carla_mpc_node", output="screen",
        # regions_npz MUST be passed. It defaults to Town05 inside the node, so on any
        # other town the MPC would score its rollouts against a DIFFERENT TOWN'S road
        # network — a drivable-surface penalty computed from geometry the vehicle is
        # nowhere near, which shows up as a persistent one-sided steering bias.
        parameters=[{"role_name": role, "odom_topic": odom, "regions_npz": regions,
                     # The road corridor is a STAND-IN for obstacle sensing, and the node's
                     # own note by `regions_npz` says disabling it is "the correct setting
                     # once Phase B's LiDAR provides a real EDT". That EDT is now real, so
                     # the hard reject is off; `w_offroad` still PREFERS the road, it just
                     # no longer forbids leaving it. Turning through a junction means
                     # swinging wider than a corridor derived from its adjacent roads, and
                     # the hard reject makes that crawl even with obstacles well clear.
                     "reject_offroad": False,
                     "guidance": LaunchConfiguration("guidance"),
                     "safety_radius": ParameterValue(
                         LaunchConfiguration("safety_radius"), value_type=float),
                     "aim_source": LaunchConfiguration("aim_source"),
                     "controller": LaunchConfiguration("controller"),
                     "terrain_source": LaunchConfiguration("terrain_source"),
                     "overlay_every_n": ParameterValue(
                         LaunchConfiguration("overlay_every_n"), value_type=int),
                     "forbid_terrain": LaunchConfiguration("forbid_terrain"),
                     "terrain_decay_m": ParameterValue(
                         LaunchConfiguration("terrain_decay_m"), value_type=float),
                     "cam_x": ParameterValue(LaunchConfiguration("cam_x"), value_type=float),
                     # The MPC needs the height above the ROAD; `cam_z` is the mount on the
                     # vehicle. ~1.573 for a 1.5 mount, because CARLA's vehicle origin does
                     # not sit on the road surface. Kept as its own argument so
                     # the difference is visible rather than folded in.
                     "cam_z": ParameterValue(LaunchConfiguration("cam_z"), value_type=float),
                     "cam_fov": ParameterValue(LaunchConfiguration("cam_fov"), value_type=float),
                     "cam_pitch_down_deg": ParameterValue(
                         LaunchConfiguration("cam_pitch_down_deg"), value_type=float),
                     "kappa_max": ParameterValue(LaunchConfiguration("kappa_max"),
                                                 value_type=float),
                     "arc_len_m": ParameterValue(LaunchConfiguration("arc_len_m"),
                                                 value_type=float),
                     "w_obstacle": ParameterValue(
                         LaunchConfiguration("w_obstacle"), value_type=float),
                     "fan_segments": ParameterValue(
                         LaunchConfiguration("fan_segments"), value_type=int),
                     "fan_size": ParameterValue(LaunchConfiguration("fan_size"),
                                                value_type=int),
                     "pure_pursuit": ParameterValue(
                         LaunchConfiguration("pure_pursuit"), value_type=bool),
                     "seed": ParameterValue(
                         LaunchConfiguration("mpc_seed"), value_type=int),
                     "distortion_model": LaunchConfiguration("distortion_model"),
                     "distortion_jitter_frac": ParameterValue(
                         LaunchConfiguration("distortion_jitter_frac"),
                         value_type=float),
                     "distortion_pivot": LaunchConfiguration("distortion_pivot"),
                     "distortion_surface": ParameterValue(
                         LaunchConfiguration("distortion_surface"), value_type=bool),
                     **{f"distortion_{k}": ParameterValue(
                         LaunchConfiguration(f"distortion_{k}"), value_type=float)
                        for k in ("angle_deg", "scale", "tx", "ty",
                                  "jitter_m", "region_rot_deg")},
                     "collision_horizon": ParameterValue(
                         LaunchConfiguration("collision_horizon"), value_type=int),
                     "v_max": LaunchConfiguration("v_max"),
                     "decide_v_max": LaunchConfiguration("decide_v_max"),
                     "require_ranges": False,
                     "dry_run": LaunchConfiguration("dry_run"),
                     # ints, not the raw LaunchConfiguration: these are declared as
                     # integer parameters on the node, and a launch substitution arrives
                     # as a string, which rclpy rejects at declare time
                     "mpc_K": ParameterValue(LaunchConfiguration("mpc_K"),
                                             value_type=int),
                     "mpc_N": ParameterValue(LaunchConfiguration("mpc_N"),
                                             value_type=int),
                     "control_every_n_odom": ParameterValue(
                         LaunchConfiguration("control_every_n_odom"), value_type=int),
                     }, SIM_TIME])

    # Load the plan a few seconds in: the plan is latched so ordering does not strictly
    # matter, but brain must be up for the /brain/load_plan service call to land, and
    # waiting is clearer in the log than a failed call followed by a manual retry.
    load = TimerAction(period=5.0, actions=[
        Node(package="carla_gt_bridge", executable="load_mission_node",
             name="load_mission_node", output="screen",
             parameters=[{"plan_file": LaunchConfiguration("plan_file")}, SIM_TIME])])

    return LaunchDescription(
        args + [gt_cluster, cluster_guard, gt_cue, lidar_ranges, terrain_mask, brain, mpc, load])
    # load stays in llm mode too: the MPC takes the region GEOMETRY (centroids, bearings) from the latched
    # /brain/incoming_plan, and without it sits on "waiting for /brain/incoming_plan" forever. Its
    # /brain/load_plan service call then times out harmlessly -- no plan-tree brain is listening.
